# Linter configuruation.
[tool.isort]
profile = "black"
atomic = true
extend_skip_glob = "migrations,scripts"
line_length = 88


[tool.black]
extend-exclude = "migrations,scripts"


[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
warn_no_return = false
warn_unused_ignores = false
allow_untyped_globals = true
allow_redefinition = true
pretty = true
exclude = "build|dist|tests"

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true


# PEP-517 compliant build system
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
  "mypy"
]

build-backend = "setuptools.build_meta"
